{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8ad06cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n",
      "3\n",
      "False\n",
      "2\n",
      "1\n",
      "True\n"
     ]
    }
   ],
   "source": [
    "'''Task Description #1 – Stack Implementation\n",
    "Use AI to generate a Stack class with push, pop, peek, and is_empty methods.\n",
    "Sample Input Code:\n",
    "class Stack:\n",
    "pass\n",
    "Expected Output:\n",
    "• A functional stack implementation with all required methods and\n",
    "docstrings.'''\n",
    "class Stack:\n",
    "    \"\"\"A simple implementation of a stack data structure.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty stack.\"\"\"\n",
    "        self.items = []\n",
    "\n",
    "    def push(self, item):\n",
    "        \"\"\"Add an item to the top of the stack.\n",
    "\n",
    "        Args:\n",
    "            item: The item to be added to the stack.\n",
    "        \"\"\"\n",
    "        self.items.append(item)\n",
    "\n",
    "    def pop(self):\n",
    "        \"\"\"Remove and return the item at the top of the stack.\n",
    "\n",
    "        Returns:\n",
    "            The item at the top of the stack.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If the stack is empty.\n",
    "        \"\"\"\n",
    "        if self.is_empty():\n",
    "            raise IndexError(\"Pop from an empty stack\")\n",
    "        return self.items.pop()\n",
    "\n",
    "    def peek(self):\n",
    "        \"\"\"Return the item at the top of the stack without removing it.\n",
    "\n",
    "        Returns:\n",
    "            The item at the top of the stack.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If the stack is empty.\n",
    "        \"\"\"\n",
    "        if self.is_empty():\n",
    "            raise IndexError(\"Peek from an empty stack\")\n",
    "        return self.items[-1]\n",
    "\n",
    "    def is_empty(self):\n",
    "        \"\"\"Check if the stack is empty.\n",
    "\n",
    "        Returns:\n",
    "            True if the stack is empty, False otherwise.\n",
    "        \"\"\"\n",
    "        return len(self.items) == 0\n",
    "\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    stack = Stack()\n",
    "    stack.push(1)\n",
    "    stack.push(2)\n",
    "    stack.push(3)\n",
    "\n",
    "    print(stack.peek())  # Output: 3\n",
    "    print(stack.pop())   # Output: 3\n",
    "    print(stack.is_empty())  # Output: False\n",
    "    print(stack.pop())   # Output: 2\n",
    "    print(stack.pop())   # Output: 1\n",
    "    print(stack.is_empty())  # Output: True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ef68c594",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "1\n",
      "2\n",
      "2\n",
      "3\n",
      "True\n"
     ]
    }
   ],
   "source": [
    "'''Task: Use AI to implement a Queue using Python lists.\n",
    "Sample Input Code:\n",
    "class Queue:\n",
    "pass\n",
    "Expected Output:\n",
    "• FIFO-based queue class with enqueue, dequeue, peek, and size\n",
    "methods.'''\n",
    "class Queue:\n",
    "    \"\"\"A simple implementation of a queue data structure.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty queue.\"\"\"\n",
    "        self.items = []\n",
    "\n",
    "    def enqueue(self, item):\n",
    "        \"\"\"Add an item to the end of the queue.\n",
    "\n",
    "        Args:\n",
    "            item: The item to be added to the queue.\n",
    "        \"\"\"\n",
    "        self.items.append(item)\n",
    "\n",
    "    def dequeue(self):\n",
    "        \"\"\"Remove and return the item at the front of the queue.\n",
    "\n",
    "        Returns:\n",
    "            The item at the front of the queue.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If the queue is empty.\n",
    "        \"\"\"\n",
    "        if self.is_empty():\n",
    "            raise IndexError(\"Dequeue from an empty queue\")\n",
    "        return self.items.pop(0)\n",
    "\n",
    "    def peek(self):\n",
    "        \"\"\"Return the item at the front of the queue without removing it.\n",
    "\n",
    "        Returns:\n",
    "            The item at the front of the queue.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If the queue is empty.\n",
    "        \"\"\"\n",
    "        if self.is_empty():\n",
    "            raise IndexError(\"Peek from an empty queue\")\n",
    "        return self.items[0]\n",
    "\n",
    "    def size(self):\n",
    "        \"\"\"Return the number of items in the queue.\n",
    "\n",
    "        Returns:\n",
    "            The number of items in the queue.\n",
    "        \"\"\"\n",
    "        return len(self.items)\n",
    "\n",
    "    def is_empty(self):\n",
    "        \"\"\"Check if the queue is empty.\n",
    "\n",
    "        Returns:\n",
    "            True if the queue is empty, False otherwise.\n",
    "        \"\"\"\n",
    "        return len(self.items) == 0\n",
    "    \n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    queue = Queue()\n",
    "    queue.enqueue(1)\n",
    "    queue.enqueue(2)\n",
    "    queue.enqueue(3)\n",
    "\n",
    "    print(queue.peek())  # Output: 1\n",
    "    print(queue.dequeue())  # Output: 1\n",
    "    print(queue.size())  # Output: 2\n",
    "    print(queue.dequeue())  # Output: 2\n",
    "    print(queue.dequeue())  # Output: 3\n",
    "    print(queue.is_empty())  # Output: True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "abd8789d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 2 3 \n"
     ]
    }
   ],
   "source": [
    "'''Task Description #3 – Linked List\n",
    "Task: Use AI to generate a Singly Linked List with insert and display\n",
    "methods.\n",
    "Sample Input Code:\n",
    "class Node:\n",
    "pass\n",
    "class LinkedList:\n",
    "pass\n",
    "Expected Output:\n",
    "• A working linked list implementation with clear method\n",
    "documentation and functionality.'''\n",
    "class Node:\n",
    "    \"\"\"A node in a singly linked list.\"\"\"\n",
    "\n",
    "    def __init__(self, data):\n",
    "        \"\"\"Initialize a node with data and a reference to the next node.\n",
    "\n",
    "        Args:\n",
    "            data: The data stored in the node.\n",
    "        \"\"\"\n",
    "        self.data = data\n",
    "        self.next = None\n",
    "class LinkedList:\n",
    "    \"\"\"A simple implementation of a singly linked list.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty linked list.\"\"\"\n",
    "        self.head = None\n",
    "\n",
    "    def insert(self, data):\n",
    "        \"\"\"Insert a new node with the given data at the end of the list.\n",
    "\n",
    "        Args:\n",
    "            data: The data to be stored in the new node.\n",
    "        \"\"\"\n",
    "        new_node = Node(data)\n",
    "        if self.head is None:\n",
    "            self.head = new_node\n",
    "            return\n",
    "        last_node = self.head\n",
    "        while last_node.next:\n",
    "            last_node = last_node.next\n",
    "        last_node.next = new_node\n",
    "\n",
    "    def display(self):\n",
    "        \"\"\"Display the contents of the linked list.\"\"\"\n",
    "        current_node = self.head\n",
    "        while current_node:\n",
    "            print(current_node.data, end=' ')\n",
    "            current_node = current_node.next\n",
    "        print()\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    linked_list = LinkedList()\n",
    "    linked_list.insert(1)\n",
    "    linked_list.insert(2)\n",
    "    linked_list.insert(3)\n",
    "\n",
    "    linked_list.display()  # Output: 1 2 3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "6830dac5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2, 3, 4, 5, 7]\n"
     ]
    }
   ],
   "source": [
    "'''Task Description #4 – Binary Search Tree (BST)\n",
    "Task: Use AI to create a BST with insert and in-order traversal methods.\n",
    "Sample Input Code:\n",
    "class BST:\n",
    "pass\n",
    "Expected Output:\n",
    "• BST implementation with recursive insert and traversal methods.'''\n",
    "class Node:\n",
    "    \"\"\"A node in a binary search tree.\"\"\"\n",
    "\n",
    "    def __init__(self, data):\n",
    "        \"\"\"Initialize a node with data and references to left and right children.\n",
    "\n",
    "        Args:\n",
    "            data: The data stored in the node.\n",
    "        \"\"\"\n",
    "        self.data = data\n",
    "        self.left = None\n",
    "        self.right = None\n",
    "class BST:\n",
    "    \"\"\"A simple implementation of a binary search tree.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty binary search tree.\"\"\"\n",
    "        self.root = None\n",
    "\n",
    "    def insert(self, data):\n",
    "        \"\"\"Insert a new node with the given data into the BST.\n",
    "\n",
    "        Args:\n",
    "            data: The data to be stored in the new node.\n",
    "        \"\"\"\n",
    "        if self.root is None:\n",
    "            self.root = Node(data)\n",
    "        else:\n",
    "            self._insert_recursive(self.root, data)\n",
    "\n",
    "    def _insert_recursive(self, node, data):\n",
    "        \"\"\"Helper method to insert a new node recursively.\n",
    "\n",
    "        Args:\n",
    "            node: The current node in the BST.\n",
    "            data: The data to be inserted.\n",
    "        \"\"\"\n",
    "        if data < node.data:\n",
    "            if node.left is None:\n",
    "                node.left = Node(data)\n",
    "            else:\n",
    "                self._insert_recursive(node.left, data)\n",
    "        else:\n",
    "            if node.right is None:\n",
    "                node.right = Node(data)\n",
    "            else:\n",
    "                self._insert_recursive(node.right, data)\n",
    "\n",
    "    def in_order_traversal(self):\n",
    "        \"\"\"Perform in-order traversal of the BST and return a list of values.\"\"\"\n",
    "        return self._in_order_recursive(self.root)\n",
    "\n",
    "    def _in_order_recursive(self, node):\n",
    "        \"\"\"Helper method for in-order traversal recursively.\n",
    "\n",
    "        Args:\n",
    "            node: The current node in the BST.\n",
    "\n",
    "        Returns:\n",
    "            A list of values from the in-order traversal.\n",
    "        \"\"\"\n",
    "        result = []\n",
    "        if node:\n",
    "            result.extend(self._in_order_recursive(node.left))\n",
    "            result.append(node.data)\n",
    "            result.extend(self._in_order_recursive(node.right))\n",
    "        return result\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    bst = BST()\n",
    "    bst.insert(5)\n",
    "    bst.insert(3)\n",
    "    bst.insert(7)\n",
    "    bst.insert(2)\n",
    "    bst.insert(4)\n",
    "\n",
    "    print(bst.in_order_traversal())  # Output: [2, 3, 4, 5, 7]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "58527cea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Alice\n",
      "30\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "'''Task Description #5 – Hash Table\n",
    "Task: Use AI to implement a hash table with basic insert, search, and\n",
    "delete methods.\n",
    "Sample Input Code:\n",
    "class HashTable:\n",
    "pass\n",
    "Expected Output:\n",
    "• Collision handling using chaining, with well-commented methods'''\n",
    "class HashTable:\n",
    "    \"\"\"A simple implementation of a hash table using chaining for collision handling.\"\"\"\n",
    "\n",
    "    def __init__(self, size=10):\n",
    "        \"\"\"Initialize the hash table with a specified size.\n",
    "\n",
    "        Args:\n",
    "            size: The size of the hash table (default is 10).\n",
    "        \"\"\"\n",
    "        self.size = size\n",
    "        self.table = [[] for _ in range(size)]\n",
    "\n",
    "    def _hash(self, key):\n",
    "        \"\"\"Generate a hash for the given key.\n",
    "\n",
    "        Args:\n",
    "            key: The key to be hashed.\n",
    "\n",
    "        Returns:\n",
    "            An index in the hash table.\n",
    "        \"\"\"\n",
    "        return hash(key) % self.size\n",
    "\n",
    "    def insert(self, key, value):\n",
    "        \"\"\"Insert a key-value pair into the hash table.\n",
    "\n",
    "        Args:\n",
    "            key: The key to be inserted.\n",
    "            value: The value associated with the key.\n",
    "        \"\"\"\n",
    "        index = self._hash(key)\n",
    "        # Check if the key already exists and update it\n",
    "        for i, (k, v) in enumerate(self.table[index]):\n",
    "            if k == key:\n",
    "                self.table[index][i] = (key, value)\n",
    "                return\n",
    "        # If the key does not exist, add a new key-value pair\n",
    "        self.table[index].append((key, value))\n",
    "\n",
    "    def search(self, key):\n",
    "        \"\"\"Search for a value by its key in the hash table.\n",
    "\n",
    "        Args:\n",
    "            key: The key to be searched.\n",
    "\n",
    "        Returns:\n",
    "            The value associated with the key if found, else None.\n",
    "        \"\"\"\n",
    "        index = self._hash(key)\n",
    "        for k, v in self.table[index]:\n",
    "            if k == key:\n",
    "                return v\n",
    "        return None\n",
    "\n",
    "    def delete(self, key):\n",
    "        \"\"\"Delete a key-value pair from the hash table.\n",
    "\n",
    "        Args:\n",
    "            key: The key to be deleted.\n",
    "        \"\"\"\n",
    "        index = self._hash(key)\n",
    "        for i, (k, v) in enumerate(self.table[index]):\n",
    "            if k == key:\n",
    "                del self.table[index][i]\n",
    "                return\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    hash_table = HashTable()\n",
    "    hash_table.insert(\"name\", \"Alice\")\n",
    "    hash_table.insert(\"age\", 30)\n",
    "\n",
    "    print(hash_table.search(\"name\"))  # Output: Alice\n",
    "    print(hash_table.search(\"age\"))   # Output: 30\n",
    "\n",
    "    hash_table.delete(\"name\")\n",
    "    print(hash_table.search(\"name\"))  # Output: None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a48dc869",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A: B, C\n",
      "B: A\n",
      "C: A\n"
     ]
    }
   ],
   "source": [
    "'''Task Description #6 – Graph Representation\n",
    "Task: Use AI to implement a graph using an adjacency list.\n",
    "Sample Input Code:\n",
    "class Graph:\n",
    "pass\n",
    "Expected Output:\n",
    "• Graph with methods to add vertices, add edges, and display\n",
    "connections.'''\n",
    "class Graph:\n",
    "    \"\"\"A simple implementation of a graph using an adjacency list.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty graph.\"\"\"\n",
    "        self.graph = {}\n",
    "\n",
    "    def add_vertex(self, vertex):\n",
    "        \"\"\"Add a vertex to the graph.\n",
    "\n",
    "        Args:\n",
    "            vertex: The vertex to be added.\n",
    "        \"\"\"\n",
    "        if vertex not in self.graph:\n",
    "            self.graph[vertex] = []\n",
    "\n",
    "    def add_edge(self, vertex1, vertex2):\n",
    "        \"\"\"Add an edge between two vertices in the graph.\n",
    "\n",
    "        Args:\n",
    "            vertex1: The first vertex.\n",
    "            vertex2: The second vertex.\n",
    "        \"\"\"\n",
    "        if vertex1 in self.graph and vertex2 in self.graph:\n",
    "            self.graph[vertex1].append(vertex2)\n",
    "            self.graph[vertex2].append(vertex1)\n",
    "\n",
    "    def display(self):\n",
    "        \"\"\"Display the connections in the graph.\"\"\"\n",
    "        for vertex, edges in self.graph.items():\n",
    "            print(f\"{vertex}: {', '.join(edges)}\")\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    graph = Graph()\n",
    "    graph.add_vertex(\"A\")\n",
    "    graph.add_vertex(\"B\")\n",
    "    graph.add_vertex(\"C\")\n",
    "\n",
    "    graph.add_edge(\"A\", \"B\")\n",
    "    graph.add_edge(\"A\", \"C\")\n",
    "\n",
    "    graph.display()\n",
    "    # Output:\n",
    "    # A: B, C\n",
    "    # B: A\n",
    "    # C: A"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "bac622a8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Priority Queue:\n",
      "Priority: 1, Item: Task 2\n",
      "Priority: 2, Item: Task 1\n",
      "Priority: 3, Item: Task 3\n",
      "\n",
      "Dequeue: Task 2\n",
      "\n",
      "Priority Queue after dequeue:\n",
      "Priority: 2, Item: Task 1\n",
      "Priority: 3, Item: Task 3\n"
     ]
    }
   ],
   "source": [
    "'''Task Description #7 – Priority Queue\n",
    "Task: Use AI to implement a priority queue using Python’s heapq\n",
    "module.\n",
    "Sample Input Code:\n",
    "class PriorityQueue:\n",
    "pass\n",
    "Expected Output:\n",
    "• Implementation with enqueue (priority), dequeue (highest priority),\n",
    "and display methods.'''\n",
    "import heapq\n",
    "class PriorityQueue:\n",
    "    \"\"\"A simple implementation of a priority queue using Python's heapq module.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty priority queue.\"\"\"\n",
    "        self.elements = []\n",
    "\n",
    "    def enqueue(self, item, priority):\n",
    "        \"\"\"Add an item to the priority queue with a given priority.\n",
    "\n",
    "        Args:\n",
    "            item: The item to be added to the queue.\n",
    "            priority: The priority of the item (lower values indicate higher priority).\n",
    "        \"\"\"\n",
    "        heapq.heappush(self.elements, (priority, item))\n",
    "\n",
    "    def dequeue(self):\n",
    "        \"\"\"Remove and return the item with the highest priority from the queue.\n",
    "\n",
    "        Returns:\n",
    "            The item with the highest priority.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If the priority queue is empty.\n",
    "        \"\"\"\n",
    "        if not self.elements:\n",
    "            raise IndexError(\"Dequeue from an empty priority queue\")\n",
    "        return heapq.heappop(self.elements)[1]\n",
    "\n",
    "    def display(self):\n",
    "        \"\"\"Display the items in the priority queue.\"\"\"\n",
    "        for priority, item in sorted(self.elements):\n",
    "            print(f\"Priority: {priority}, Item: {item}\")\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    pq = PriorityQueue()\n",
    "    pq.enqueue(\"Task 1\", priority=2)\n",
    "    pq.enqueue(\"Task 2\", priority=1)\n",
    "    pq.enqueue(\"Task 3\", priority=3)\n",
    "\n",
    "    print(\"Priority Queue:\")\n",
    "    pq.display()\n",
    "\n",
    "    print(\"\\nDequeue:\", pq.dequeue())  # Output: Task 2\n",
    "    print(\"\\nPriority Queue after dequeue:\")\n",
    "    pq.display()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "51681827",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Deque after insertions:\n",
      "Deque contents: ['Task 0', 'Task 1', 'Task 2']\n",
      "\n",
      "Remove from front: Task 0\n",
      "Remove from rear: Task 2\n",
      "\n",
      "Deque after removals:\n",
      "Deque contents: ['Task 1']\n"
     ]
    }
   ],
   "source": [
    "'''Task Description #8 – Deque\n",
    "Task: Use AI to implement a double-ended queue using\n",
    "collections.deque.\n",
    "Sample Input Code:\n",
    "class DequeDS:\n",
    "pass\n",
    "Expected Output:\n",
    "• Insert and remove from both ends with docstrings.'''\n",
    "from collections import deque\n",
    "class DequeDS:\n",
    "    \"\"\"A simple implementation of a double-ended queue using collections.deque.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty deque.\"\"\"\n",
    "        self.deque = deque()\n",
    "\n",
    "    def insert_front(self, item):\n",
    "        \"\"\"Insert an item at the front of the deque.\n",
    "\n",
    "        Args:\n",
    "            item: The item to be inserted at the front.\n",
    "        \"\"\"\n",
    "        self.deque.appendleft(item)\n",
    "\n",
    "    def insert_rear(self, item):\n",
    "        \"\"\"Insert an item at the rear of the deque.\n",
    "\n",
    "        Args:\n",
    "            item: The item to be inserted at the rear.\n",
    "        \"\"\"\n",
    "        self.deque.append(item)\n",
    "\n",
    "    def remove_front(self):\n",
    "        \"\"\"Remove and return the item at the front of the deque.\n",
    "\n",
    "        Returns:\n",
    "            The item at the front of the deque.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If the deque is empty.\n",
    "        \"\"\"\n",
    "        if not self.deque:\n",
    "            raise IndexError(\"Remove from an empty deque\")\n",
    "        return self.deque.popleft()\n",
    "\n",
    "    def remove_rear(self):\n",
    "        \"\"\"Remove and return the item at the rear of the deque.\n",
    "\n",
    "        Returns:\n",
    "            The item at the rear of the deque.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If the deque is empty.\n",
    "        \"\"\"\n",
    "        if not self.deque:\n",
    "            raise IndexError(\"Remove from an empty deque\")\n",
    "        return self.deque.pop()\n",
    "\n",
    "    def display(self):\n",
    "        \"\"\"Display the contents of the deque.\"\"\"\n",
    "        print(\"Deque contents:\", list(self.deque))\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    deque_ds = DequeDS()\n",
    "    deque_ds.insert_rear(\"Task 1\")\n",
    "    deque_ds.insert_rear(\"Task 2\")\n",
    "    deque_ds.insert_front(\"Task 0\")\n",
    "\n",
    "    print(\"Deque after insertions:\")\n",
    "    deque_ds.display()\n",
    "\n",
    "    print(\"\\nRemove from front:\", deque_ds.remove_front())  # Output: Task 0\n",
    "    print(\"Remove from rear:\", deque_ds.remove_rear())    # Output: Task 2\n",
    "\n",
    "    print(\"\\nDeque after removals:\")\n",
    "    deque_ds.display()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b8d31afc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Order placed: Student A: Sandwich\n",
      "Order placed: Student B: Salad\n",
      "Order placed: Student C: Juice\n",
      "Pending orders:\n",
      "Student A: Sandwich\n",
      "Student B: Salad\n",
      "Student C: Juice\n",
      "Order served: Student A: Sandwich\n",
      "Order served: Student B: Salad\n",
      "Pending orders:\n",
      "Student C: Juice\n"
     ]
    }
   ],
   "source": [
    "'''You are a programming assistant. Help design a **Campus Resource Management System** using appropriate data structures.\n",
    "\n",
    "Tasks:\n",
    "\n",
    "1. For each of the following features, choose the **most suitable data structure** from this list:\n",
    "   Stack, Queue, Priority Queue, Linked List, Binary Search Tree (BST), Graph, Hash Table, Deque.\n",
    "\n",
    "Features:\n",
    "\n",
    "* Student Attendance Tracking (daily log of students entering/exiting campus)\n",
    "* Event Registration System (manage participants with quick search and removal)\n",
    "* Library Book Borrowing (track available books and due dates)\n",
    "* Bus Scheduling System (maintain bus routes and stop connections)\n",
    "* Cafeteria Order Queue (serve students in order of arrival)\n",
    "\n",
    "2. Create a **table** with:\n",
    "   Feature | Selected Data Structure | Justification (2–3 sentences).\n",
    "\n",
    "3. Select **one feature** and implement it as a **working Python program** using the chosen data structure.\n",
    "\n",
    "4. The Python code should include:\n",
    "\n",
    "* Clear comments\n",
    "* Proper **docstrings**\n",
    "* Example usage to demonstrate functionality.\n",
    "\n",
    "Ensure the explanation is concise and the code is clean and readable.\n",
    "Feature | Selected Data Structure | Justification\n",
    "--- | --- | ---'''\n",
    "\n",
    "\n",
    "'''Student Attendance Tracking | Queue | A queue is ideal for tracking student attendance as it follows the First-In-First-Out (FIFO) principle, allowing us to log students as they enter and exit the campus in the order they arrive.\n",
    "Event Registration System | Hash Table | A hash table provides efficient insertion, search, and deletion operations, making it suitable for managing event participants where quick access to participant information is essential.\n",
    "Library Book Borrowing | Binary Search Tree (BST) | A BST allows for efficient searching, insertion, and deletion of books based on their titles or IDs, making it easier to track available books and due dates.\n",
    "Bus Scheduling System | Graph | A graph is the best choice for representing bus routes and stop connections, as it can model the relationships between stops and routes effectively, allowing for efficient pathfinding and scheduling.\n",
    "Cafeteria Order Queue | Queue | A queue is perfect for managing cafeteria orders as it ensures that students are served in the order they arrive, maintaining fairness and efficiency in the service process.'''\n",
    "\n",
    "\n",
    "'''Implementation of the Cafeteria Order Queue using a Queue data structure.''' \n",
    "class CafeteriaOrderQueue:\n",
    "    \"\"\"A class to manage cafeteria orders using a queue data structure.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty order queue.\"\"\"\n",
    "        self.orders = []\n",
    "\n",
    "    def place_order(self, order):\n",
    "        \"\"\"Place a new order in the queue.\n",
    "\n",
    "        Args:\n",
    "            order: A string representing the student's order.\n",
    "        \"\"\"\n",
    "        self.orders.append(order)\n",
    "        print(f\"Order placed: {order}\")\n",
    "\n",
    "    def serve_order(self):\n",
    "        \"\"\"Serve the next order in the queue.\n",
    "\n",
    "        Returns:\n",
    "            The next order to be served.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If there are no orders to serve.\n",
    "        \"\"\"\n",
    "        if not self.orders:\n",
    "            raise IndexError(\"No orders to serve\")\n",
    "        order = self.orders.pop(0)\n",
    "        print(f\"Order served: {order}\")\n",
    "        return order\n",
    "\n",
    "    def display_orders(self):\n",
    "        \"\"\"Display all pending orders in the queue.\"\"\"\n",
    "        if not self.orders:\n",
    "            print(\"No pending orders.\")\n",
    "        else:\n",
    "            print(\"Pending orders:\")\n",
    "            for order in self.orders:\n",
    "                print(order)\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    cafeteria_queue = CafeteriaOrderQueue()\n",
    "    cafeteria_queue.place_order(\"Student A: Sandwich\")\n",
    "    cafeteria_queue.place_order(\"Student B: Salad\")\n",
    "    cafeteria_queue.place_order(\"Student C: Juice\")\n",
    "\n",
    "    cafeteria_queue.display_orders()\n",
    "\n",
    "    cafeteria_queue.serve_order()\n",
    "    cafeteria_queue.serve_order()\n",
    "\n",
    "    cafeteria_queue.display_orders()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "a689eb1c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Order placed: Customer A: Laptop\n",
      "Order placed: Customer B: Smartphone\n",
      "Order placed: Customer C: Headphones\n",
      "Pending orders:\n",
      "Customer A: Laptop\n",
      "Customer B: Smartphone\n",
      "Customer C: Headphones\n",
      "Order processed: Customer A: Laptop\n",
      "Order processed: Customer B: Smartphone\n",
      "Pending orders:\n",
      "Customer C: Headphones\n"
     ]
    }
   ],
   "source": [
    "'''You are a programming assistant helping design a **Smart E-Commerce Platform** using appropriate data structures.\n",
    "\n",
    "Tasks:\n",
    "\n",
    "1. For each feature below, choose the **most suitable data structure** from this list:\n",
    "   Stack, Queue, Priority Queue, Linked List, Binary Search Tree (BST), Graph, Hash Table, Deque.\n",
    "\n",
    "Features:\n",
    "\n",
    "* Shopping Cart Management (add/remove products dynamically)\n",
    "* Order Processing System (orders processed in the order they are placed)\n",
    "* Top-Selling Products Tracker (products ranked by sales count)\n",
    "* Product Search Engine (fast lookup of products using product ID)\n",
    "* Delivery Route Planning (connect warehouses and delivery locations)\n",
    "\n",
    "2. Create a **table** with the following columns:\n",
    "   Feature | Selected Data Structure | Justification (2–3 sentences).\n",
    "\n",
    "3. Choose **one feature** and implement it as a **working Python program** using the selected data structure.\n",
    "\n",
    "4. The program should include:\n",
    "\n",
    "* Clear comments\n",
    "* Proper **docstrings**\n",
    "* A short **example demonstrating the functionality**.\n",
    "\n",
    "Ensure the explanation is concise and the Python code is clean and easy to understand.\n",
    "Feature | Selected Data Structure | Justification\n",
    "--- | --- | ---\n",
    "Shopping Cart Management | Linked List | A linked list allows for dynamic addition and removal of products in\n",
    "the shopping cart without needing to shift elements, making it efficient for managing a varying number of products.\n",
    "Order Processing System | Queue | A queue is ideal for processing orders in the order they are placed, following the First-In-First-Out (FIFO) principle, ensuring fairness in order handling.\n",
    "Top-Selling Products Tracker | Priority Queue | A priority queue can efficiently keep track of products ranked by sales count, allowing for quick retrieval of top-selling products based on their priority (sales count).\n",
    "Product Search Engine | Hash Table | A hash table provides fast lookup of products using product IDs,\n",
    "enabling efficient retrieval of product information in the search engine.'''\n",
    "\n",
    "#Delivery Route Planning | Graph | A graph is suitable for modeling the connections between warehouses and delivery locations, allowing for efficient route planning and optimization using algorithms like Dijkstra's or A*.\n",
    "'''Implementation of the Order Processing System using a Queue data structure.'''\n",
    "\n",
    "class OrderProcessingSystem:\n",
    "    \"\"\"A class to manage order processing using a queue data structure.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialize an empty order queue.\"\"\"\n",
    "        self.orders = []\n",
    "\n",
    "    def place_order(self, order):\n",
    "        \"\"\"Place a new order in the queue.\n",
    "\n",
    "        Args:\n",
    "            order: A string representing the customer's order.\n",
    "        \"\"\"\n",
    "        self.orders.append(order)\n",
    "        print(f\"Order placed: {order}\")\n",
    "\n",
    "    def process_order(self):\n",
    "        \"\"\"Process the next order in the queue.\n",
    "\n",
    "        Returns:\n",
    "            The next order to be processed.\n",
    "\n",
    "        Raises:\n",
    "            IndexError: If there are no orders to process.\n",
    "        \"\"\"\n",
    "        if not self.orders:\n",
    "            raise IndexError(\"No orders to process\")\n",
    "        order = self.orders.pop(0)\n",
    "        print(f\"Order processed: {order}\")\n",
    "        return order\n",
    "\n",
    "    def display_orders(self):\n",
    "        \"\"\"Display all pending orders in the queue.\"\"\"\n",
    "        if not self.orders:\n",
    "            print(\"No pending orders.\")\n",
    "        else:\n",
    "            print(\"Pending orders:\")\n",
    "            for order in self.orders:\n",
    "                print(order)\n",
    "# Example usage:\n",
    "if __name__ == \"__main__\":\n",
    "    order_system = OrderProcessingSystem()\n",
    "    order_system.place_order(\"Customer A: Laptop\")\n",
    "    order_system.place_order(\"Customer B: Smartphone\")\n",
    "    order_system.place_order(\"Customer C: Headphones\")\n",
    "\n",
    "    order_system.display_orders()\n",
    "\n",
    "    order_system.process_order()\n",
    "    order_system.process_order()\n",
    "\n",
    "    order_system.display_orders()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
