# -*- coding: utf-8 -*-
"""LAb 17 AI-AC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMz0REVbxwr6H_3Muu7g8dWnQf_HaUUw

**Task 1 Employee Dataset Cleaning**
Use AI assistance to clean an employee information dataset.
Instructions:
• Handle missing values in salary, designation, and experience
• Remove duplicate employee IDs
• Standardize text values (job titles in lowercase)
• Encode categorical features (designation, employment_type)
Expected Output:
A clean dataset suitable for HR analytics and prediction tasks.
"""

import pandas as pd
import numpy as np

# Re-creating the sample employee dataset
data = {
    'employee_id': [101, 102, 103, 104, 105, 101, 106, 107, 108, 109],
    'salary': [60000, 75000, np.nan, 50000, 90000, 60000, 65000, 80000, np.nan, 70000],
    'designation': ['Software Engineer', 'Data Scientist', np.nan, 'Project Manager', 'Software Engineer', 'Software Engineer', 'HR Specialist', 'Data Scientist', 'Marketing Analyst', 'HR Specialist'],
    'experience': [3, 5, 2, np.nan, 7, 3, 4, 6, 1, 5],
    'employment_type': ['Full-time', 'Full-time', 'Contract', 'Full-time', 'Part-time', 'Full-time', 'Contract', 'Full-time', 'Part-time', 'Full-time']
}
df = pd.DataFrame(data)

print("Sample dataset recreated:")
display(df.head())

# 2. Handle missing values
# For numerical columns (salary, experience), fill with median
# For categorical column (designation), fill with mode
df['salary'] = df['salary'].fillna(df['salary'].median())
df['experience'] = df['experience'].fillna(df['experience'].median())
df['designation'] = df['designation'].fillna(df['designation'].mode()[0])

print("Dataset after handling missing values:")
display(df.head())
print("\n" + "="*30 + "\n")

# 3. Remove duplicate employee IDs
df.drop_duplicates(subset='employee_id', keep='first', inplace=True)

print("Dataset after removing duplicate employee IDs:")
display(df.head())
print("\n" + "="*30 + "\n")

# 4. Standardize text values (job titles in lowercase)
df['designation'] = df['designation'].str.lower()

print("Dataset after standardizing designation text:")
display(df.head())
print("\n" + "="*30 + "\n")

# 5. Encode categorical features (designation, employment_type)
df_encoded = pd.get_dummies(df, columns=['designation', 'employment_type'], drop_first=True)

print("Cleaned and Encoded Dataset (first 5 rows):")
display(df_encoded.head())
print("\n" + "="*30 + "\n")

print("Cleaning process complete. The 'df_encoded' DataFrame contains the clean and transformed data.")

"""**Task 2 – Student Performance Data Preprocessing**
Task:
Preprocess student performance data using AI assistance.
Instructions:
• Convert exam_date column into datetime format
• Extract new features (month, semester, day)
• Normalize total_marks
• Detect and handle outliers in marks using IQR or Z-score
Expected Output:
A transformed dataset with time-based academic features and normalized
marks.
"""

import pandas as pd
import numpy as np

# Create a sample student performance dataset
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'exam_date': ['2023-09-15', '2023-10-20', '2023-09-10', '2023-11-05', '2023-10-01', '2023-09-25', '2023-11-10', '2023-10-15', '2023-09-01', '2023-11-20'],
    'total_marks': [85, 72, 90, 68, 78, 92, 60, 88, 95, 75],
    'subject': ['Math', 'Science', 'Math', 'English', 'Science', 'Math', 'English', 'Science', 'Math', 'English'],
    'attendance': [95, 88, 98, 75, 90, 99, 70, 92, 97, 80]
}
df_student = pd.DataFrame(data)

print("Sample Student Performance Dataset:")
display(df_student.head())

# Placeholder to import your own dataset
# If you have a CSV file named 'student_data.csv', you can load it like this:
# df_student = pd.read_csv('student_data.csv')
# Ensure your dataset has 'exam_date' and 'total_marks' columns, and adjust other column names as needed.

print("\n" + "="*30 + "\n")

# 1. Convert exam_date column into datetime format
df_student['exam_date'] = pd.to_datetime(df_student['exam_date'])

print("Dataset after converting 'exam_date' to datetime:")
display(df_student.head())

# 2. Extract new features (month, semester, day)
df_student['exam_month'] = df_student['exam_date'].dt.month
df_student['exam_day'] = df_student['exam_date'].dt.day
# Assuming a simple semester division for demonstration: Sep-Dec is Fall (1), Jan-Aug is Spring/Summer (2)
df_student['semester'] = df_student['exam_month'].apply(lambda x: 1 if x >= 9 and x <= 12 else 2)

print("Dataset after extracting new date features:")
display(df_student.head())

# 3. Normalize total_marks (Min-Max Normalization)
min_marks = df_student['total_marks'].min()
max_marks = df_student['total_marks'].max()
df_student['normalized_marks'] = (df_student['total_marks'] - min_marks) / (max_marks - min_marks)

print("Dataset after normalizing 'total_marks':")
display(df_student.head())

# 4. Detect and handle outliers in marks using IQR
Q1 = df_student['total_marks'].quantile(0.25)
Q3 = df_student['total_marks'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identifying outliers
outliers = df_student[(df_student['total_marks'] < lower_bound) | (df_student['total_marks'] > upper_bound)]

print(f"\nDetected Outliers in total_marks (using IQR, if any):\n{outliers}")

# Handling outliers: Cap them at the bounds (you could also remove them or use other methods)
df_student['total_marks_handled'] = df_student['total_marks'].clip(lower=lower_bound, upper=upper_bound)

print("\nDataset after handling outliers in 'total_marks' (capped):")
display(df_student.head())

print("\n" + "="*30 + "\n")
print("Student performance data preprocessing complete.")

"""**Task 3 – Student Health Data Preparation**
Task:
Clean and preprocess student health records using AI scripts.
Instructions:
• Handle missing values in height, weight, BMI
• Encode categorical features (medical_condition, fitness_status)
• Scale numerical features using standard scaling
• Split dataset into training and testing sets
Expected Output:
A preprocessed dataset ready for predictive health analysis.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# 1. Create a sample student health dataset
data_health = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'height_cm': [170, 165, np.nan, 180, 175, 160, 172, 185, np.nan, 168],
    'weight_kg': [65, 58, 70, 75, np.nan, 55, 68, 80, 62, np.nan],
    'BMI': [22.5, 21.3, 23.8, np.nan, 24.5, 21.5, 23.0, 23.5, 22.0, 21.8],
    'medical_condition': ['None', 'Asthma', 'None', 'Allergies', 'None', 'Asthma', 'None', 'None', 'Allergies', 'None'],
    'fitness_status': ['Fit', 'Moderate', 'Fit', 'Fit', 'Low', 'Moderate', 'Fit', 'Fit', 'Low', 'Moderate']
}
df_health = pd.DataFrame(data_health)

print("Original Student Health Dataset:")
display(df_health.head())
print("\n" + "="*30 + "\n")

# Placeholder for importing your own dataset
# df_health = pd.read_csv('student_health_data.csv')

# Define numerical and categorical features
numerical_features = ['height_cm', 'weight_kg', 'BMI']
categorical_features = ['medical_condition', 'fitness_status']

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combine preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Apply preprocessing to the dataset
df_processed = preprocessor.fit_transform(df_health)

# Get feature names for the processed DataFrame (optional, for better readability)
feature_names = numerical_features + \
                list(preprocessor.named_transformers_['cat']['onehot'].get_feature_names_out(categorical_features))

df_processed_df = pd.DataFrame(df_processed, columns=feature_names)

print("Processed Dataset (first 5 rows - after handling missing values, encoding, and scaling):")
display(df_processed_df.head())
print("\n" + "="*30 + "\n")

# 5. Split dataset into training and testing sets
# Assuming we want to predict a target variable, let's create a dummy target for demonstration
df_health['target'] = np.random.randint(0, 2, size=len(df_health)) # Dummy binary target

X = df_processed_df  # Features are the processed data
y = df_health['target'] # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\n" + "="*30 + "\n")
print("Student health data preparation complete. The dataset is split into X_train, X_test, y_train, y_test.")

"""**Task 4: Real-Time Application: Ride-Sharing Data Cleaning**
Scenario:
A ride-sharing company has trip data with errors.
Requirements:
• Standardize pickup and drop locations
• Fill missing fare amounts with median values
• Remove duplicate ride entries
• Normalize driver ratings
• Generate a summary of data improvements
Expected Output:
A clean dataset ready for operational analysis.
"""

import pandas as pd
import numpy as np

# 1. Create a sample ride-sharing dataset
data_rides = {
    'ride_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    'pickup_location': [' Downtown  ', 'Airport', 'Suburb A', 'Downtown', '  City Center', 'Airport', 'Suburb B', 'Downtown', 'City Center  ', 'Suburb A'],
    'dropoff_location': ['Uptown', '  City Center', 'Downtown', 'Suburb A', 'Airport  ', 'Suburb B', 'Uptown', 'Airport', 'Downtown', 'City Center'],
    'fare_amount': [25.50, 45.00, np.nan, 20.00, 30.75, 48.20, 15.00, np.nan, 22.00, 35.50],
    'driver_rating': [4.8, 3.5, 5.0, 4.2, np.nan, 4.9, 3.0, 4.5, 4.0, 5.0],
    'ride_timestamp': ['2023-01-01 10:00:00', '2023-01-01 10:15:00', '2023-01-01 10:30:00', '2023-01-01 10:45:00', '2023-01-01 11:00:00',
                       '2023-01-01 10:15:00', '2023-01-01 11:30:00', '2023-01-01 11:45:00', '2023-01-01 12:00:00', '2023-01-01 12:15:00']
}
df_rides = pd.DataFrame(data_rides)

print("Original Ride-Sharing Dataset:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# Placeholder for importing your own dataset
# If you have a CSV file named 'ride_data.csv', you can load it like this:
# df_rides = pd.read_csv('ride_data.csv')
# Ensure your dataset has similar columns or adjust the code as needed.

# 2. Standardize pickup and drop locations
df_rides['pickup_location'] = df_rides['pickup_location'].str.strip().str.lower()
df_rides['dropoff_location'] = df_rides['dropoff_location'].str.strip().str.lower()

print("Dataset after standardizing locations:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 3. Fill missing fare amounts with median values
df_rides['fare_amount'] = df_rides['fare_amount'].fillna(df_rides['fare_amount'].median())

print("Dataset after filling missing fare amounts:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 4. Remove duplicate ride entries (assuming 'ride_id' and 'ride_timestamp' define a unique ride)
df_rides.drop_duplicates(subset=['ride_id', 'ride_timestamp'], inplace=True)

print("Dataset after removing duplicate ride entries:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 5. Normalize driver ratings (Min-Max normalization)
# Handle potential NaN values in driver_rating before min/max calculation
df_rides['driver_rating_cleaned'] = df_rides['driver_rating'].fillna(df_rides['driver_rating'].median())
min_rating = df_rides['driver_rating_cleaned'].min()
max_rating = df_rides['driver_rating_cleaned'].max()
df_rides['normalized_driver_rating'] = (df_rides['driver_rating_cleaned'] - min_rating) / (max_rating - min_rating)

print("Dataset after normalizing driver ratings:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 6. Generate a summary of data improvements
print("Summary of Data Improvements:")
print("- Standardized 'pickup_location' and 'dropoff_location' to lowercase and removed extra spaces.")
# Calculate how many NaNs were in original fare_amount to report
original_fare_nans = pd.Series(data_rides['fare_amount']).isnull().sum()
print(f"- Filled {original_fare_nans} missing 'fare_amount' values with the median.")
# Calculate how many duplicates were removed
original_rows = len(pd.DataFrame(data_rides))
duplicate_rows_before_drop = pd.DataFrame(data_rides).duplicated(subset=['ride_id', 'ride_timestamp']).sum()
print(f"- Removed {duplicate_rows_before_drop} duplicate ride entries based on 'ride_id' and 'ride_timestamp'.")
print("- Normalized 'driver_rating' using Min-Max scaling, after filling missing values with the median.")

print("\nRide-sharing data cleaning process complete. The 'df_rides' DataFrame contains the clean and transformed data.")
display(df_rides.describe(include='all'))
